#!/usr/bin/env node
import { readInput, renderResearchResult, resolveSaveTarget, validateResearchResult } from './lib/wf-search.mjs';

const HELP = `wf-search helper (stateless)\n\nUsage:\n  node Harness/scripts/wf-search.mjs validate --input <file>|- [--json]\n  node Harness/scripts/wf-search.mjs render --input <file>|-\n  node Harness/scripts/wf-search.mjs resolve-save-target --project <root> [--task <id>] --id <report-id> [--json]\n\nThe helper performs no network access and writes no files.`;
const COMMANDS = new Set(['validate', 'render', 'resolve-save-target']);
function output(payload) { process.stdout.write(`${JSON.stringify(payload, null, 2)}\n`); }
function fail(message, code = 'WFR-CLI001') { output({ ok: false, errors: [{ code, path: '$', message }], warnings: [], summary: { overBudget: false } }); process.exitCode = 1; }
function parse(argv) { const args = { _: [] }; for (let i = 0; i < argv.length; i += 1) { const token = argv[i]; if (token === '--help' || token === '-h') { args.help = true; continue; } if (!token.startsWith('--')) { args._.push(token); continue; } const key = token.slice(2); if (key === 'json') { args.json = true; continue; } if (['input', 'project', 'task', 'id'].includes(key)) { if (!argv[i + 1] || argv[i + 1].startsWith('--')) throw new Error(`--${key} requires a value`); args[key] = argv[++i]; continue; } throw new Error(`unknown option: --${key}`); } return args; }
 function main() { let args; try { args = parse(process.argv.slice(2)); } catch (error) { fail(error.message); return; } if (args.help || args._[0] === undefined) { process.stdout.write(`${HELP}\n`); return; } const command = args._[0]; if (!COMMANDS.has(command)) { fail(`unknown command: ${command}`); return; } if (args._.length > 1) { fail(`unexpected argument: ${args._[1]}`); return; } if (command === 'render' && args.json) { fail('unknown option: --json'); return; } try { if (command === 'resolve-save-target') { output({ ok: true, ...resolveSaveTarget({ project: args.project, task: args.task, id: args.id }) }); return; } const checked = validateResearchResult(readInput(args.input)); if (command === 'validate') { output({ ok: checked.ok, errors: checked.errors, warnings: checked.warnings, summary: checked.summary, result: checked.normalized }); if (!checked.ok) process.exitCode = 1; return; } if (!checked.ok) { output({ ok: false, errors: checked.errors, warnings: checked.warnings, summary: checked.summary }); process.exitCode = 1; return; } process.stdout.write(renderResearchResult(checked.normalized)); } catch (error) { const code = typeof error?.code === 'string' && /^WFR-/.test(error.code) ? error.code : 'WFR-CLI002'; fail(error.message || String(error), code); } }
main();
