import test, { after } from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { generate, isHarnessOwnedContent, buildHarnessInterestCandidateSet } from '../src/generator.js';

const tempRoots = [];
function tmpdir() {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'harness-collision-'));
  tempRoots.push(root);
  return root;
}
after(() => {
  for (const root of tempRoots) fs.rmSync(root, { recursive: true, force: true });
});

function writeExisting(targetDir, rel, content) {
  const abs = path.join(targetDir, ...rel.split('/'));
  fs.mkdirSync(path.dirname(abs), { recursive: true });
  fs.writeFileSync(abs, content, 'utf8');
  return abs;
}

// ============================================================================
// G5a — marker-detection helper (isHarnessOwnedContent)
// ============================================================================

test('isHarnessOwnedContent detects frontmatter harness: wf-agent marker', () => {
  const content = '---\nharness: wf-agent\n---\n# Planner\n\nYou plan tasks.\n';
  assert.equal(isHarnessOwnedContent(content), true);
});

test('isHarnessOwnedContent detects frontmatter harness: wf-framework marker', () => {
  const content = '---\nharness: wf-framework\n---\nbody\n';
  assert.equal(isHarnessOwnedContent(content), true);
});

test('isHarnessOwnedContent detects body WF-MAX marker', () => {
  const content = 'Some agent notes.\nFollows WF-MAX rules.\n';
  assert.equal(isHarnessOwnedContent(content), true);
});

test('isHarnessOwnedContent detects body create-harness-vibe-coding marker', () => {
  const content = 'Generated by create-harness-vibe-coding for the project.\n';
  assert.equal(isHarnessOwnedContent(content), true);
});

test('isHarnessOwnedContent returns false for a plain user agent without markers', () => {
  const plain = 'You are a helpful coding assistant. Write clean code and review pull requests.';
  assert.equal(isHarnessOwnedContent(plain), false);
});

test('isHarnessOwnedContent returns false for a plain user command without markers', () => {
  const plain = 'My own command listing.\nNo harness references here.\n';
  assert.equal(isHarnessOwnedContent(plain), false);
});

test('isHarnessOwnedContent returns false for body mentioning /wf and /wf-max but no Harness identity', () => {
  // RISK-1 regression: the bare /wf substring marker was dropped because it
  // false-matched user files that merely mention /wf commands.
  const plain = 'My notes about the /wf and /wf-max commands I read about.\nNo harness identity here.\n';
  assert.equal(isHarnessOwnedContent(plain), false);
});

// ============================================================================
// G5c — install collision for agents (user-owned preserved, Harness-owned upgraded)
// ============================================================================

test('install preserves a user-owned .claude/agents/planner.md (no marker) even under overwrite policy', () => {
  const root = tmpdir();
  const targetDir = path.join(root, 'agent-user');
  const userPlanner = 'My personal planner agent.\nPlans things my way.\n';
  writeExisting(targetDir, '.claude/agents/planner.md', userPlanner);

  const result = generate({ projectName: 'agent-user', targetDir, onConflict: 'overwrite' });

  assert.equal(result.success, true);
  assert.ok(result.plan.skip.includes('.claude/agents/planner.md'));
  assert.equal(result.plan.overwrite.includes('.claude/agents/planner.md'), false);
  assert.equal(
    fs.readFileSync(path.join(targetDir, '.claude/agents/planner.md'), 'utf8'),
    userPlanner,
  );
});

test('install blocks a user-owned .claude/agents/planner.md (no marker) under fail policy and preserves the file', () => {
  const root = tmpdir();
  const targetDir = path.join(root, 'agent-user-fail');
  const userPlanner = 'My personal planner agent.\nPlans things my way.\n';
  writeExisting(targetDir, '.claude/agents/planner.md', userPlanner);

  const result = generate({ projectName: 'agent-user-fail', targetDir, onConflict: 'fail' });

  assert.equal(result.success, false);
  assert.ok(result.plan.conflict.includes('.claude/agents/planner.md'));
  assert.equal(result.plan.skip.includes('.claude/agents/planner.md'), false);
  assert.equal(result.plan.overwrite.includes('.claude/agents/planner.md'), false);
  assert.equal(
    fs.readFileSync(path.join(targetDir, '.claude/agents/planner.md'), 'utf8'),
    userPlanner,
  );
});

test('install skips a user-authored agent mentioning /wf text (no marker) under overwrite, warns, and preserves it', () => {
  // RISK-1 + RISK-2 regression: a user agent whose body merely mentions /wf
  // or /wf-max (but has no Harness marker) must stay user-owned -> skipped
  // (not overwritten) and emit a visible preservation warning.
  const root = tmpdir();
  const targetDir = path.join(root, 'agent-wf-text');
  const userPlanner = 'My personal planner.\nI reference /wf and /wf-max in my notes.\nNo harness identity.\n';
  writeExisting(targetDir, '.claude/agents/planner.md', userPlanner);

  assert.equal(isHarnessOwnedContent(userPlanner), false);

  const result = generate({ projectName: 'agent-wf-text', targetDir, onConflict: 'overwrite' });

  assert.equal(result.success, true);
  assert.ok(result.plan.skip.includes('.claude/agents/planner.md'));
  assert.equal(result.plan.overwrite.includes('.claude/agents/planner.md'), false);
  assert.ok(
    result.warnings.some(w => /\.claude\/agents\/planner\.md/.test(w) && /no Harness marker/.test(w)),
    JSON.stringify(result.warnings),
  );
  assert.equal(
    fs.readFileSync(path.join(targetDir, '.claude/agents/planner.md'), 'utf8'),
    userPlanner,
  );
});

test('install overwrites a Harness-owned .claude/agents/planner.md (marker present) under overwrite policy', () => {
  const root = tmpdir();
  const targetDir = path.join(root, 'agent-harness');
  const oldHarness = '---\nharness: wf-agent\n---\nOld harness planner body.\n';
  writeExisting(targetDir, '.claude/agents/planner.md', oldHarness);

  const result = generate({ projectName: 'agent-harness', targetDir, onConflict: 'overwrite' });

  assert.equal(result.success, true);
  assert.ok(result.plan.overwrite.includes('.claude/agents/planner.md'));
  const after = fs.readFileSync(path.join(targetDir, '.claude/agents/planner.md'), 'utf8');
  assert.match(after, /harness: wf-agent/);
  assert.notEqual(after, oldHarness);
});

test('install preserves a user-owned .opencode/agents/planner.md (no marker) under overwrite policy', () => {
  const root = tmpdir();
  const targetDir = path.join(root, 'opencode-agent-user');
  const userPlanner = 'OpenCode planner customized by me.\nNo markers at all.\n';
  writeExisting(targetDir, '.opencode/agents/planner.md', userPlanner);

  const result = generate({ projectName: 'opencode-agent-user', targetDir, onConflict: 'overwrite' });

  assert.equal(result.success, true);
  assert.ok(result.plan.skip.includes('.opencode/agents/planner.md'));
  assert.equal(result.plan.overwrite.includes('.opencode/agents/planner.md'), false);
  assert.equal(
    fs.readFileSync(path.join(targetDir, '.opencode/agents/planner.md'), 'utf8'),
    userPlanner,
  );
});

// ============================================================================
// G5b — install collision for commands and skills
// ============================================================================

test('install preserves a user-owned .claude/commands/wf-help.md (no marker) even under overwrite policy', () => {
  const root = tmpdir();
  const targetDir = path.join(root, 'cmd-user');
  const userCmd = 'My own command quick reference.\nNo harness markers here.\n';
  writeExisting(targetDir, '.claude/commands/wf-help.md', userCmd);

  const result = generate({ projectName: 'cmd-user', targetDir, onConflict: 'overwrite' });

  assert.equal(result.success, true);
  assert.ok(result.plan.skip.includes('.claude/commands/wf-help.md'));
  assert.equal(result.plan.overwrite.includes('.claude/commands/wf-help.md'), false);
  assert.equal(
    fs.readFileSync(path.join(targetDir, '.claude/commands/wf-help.md'), 'utf8'),
    userCmd,
  );
});

test('install overwrites a Harness-owned .claude/commands/wf-help.md (marker present) under overwrite policy', () => {
  const root = tmpdir();
  const targetDir = path.join(root, 'cmd-harness');
  const oldHarness = '---\nharness: wf-framework\n---\nOld harness command body.\n';
  writeExisting(targetDir, '.claude/commands/wf-help.md', oldHarness);

  const result = generate({ projectName: 'cmd-harness', targetDir, onConflict: 'overwrite' });

  assert.equal(result.success, true);
  assert.ok(result.plan.overwrite.includes('.claude/commands/wf-help.md'));
  const after = fs.readFileSync(path.join(targetDir, '.claude/commands/wf-help.md'), 'utf8');
  assert.match(after, /# \/wf-help/);
  assert.notEqual(after, oldHarness);
});

test('install preserves a user-owned .claude/skills/wf/SKILL.md (no marker) even under overwrite policy', () => {
  const root = tmpdir();
  const targetDir = path.join(root, 'skill-user');
  const userSkill = 'My custom wf skill notes.\nPersonal workflow steps.\n';
  writeExisting(targetDir, '.claude/skills/wf/SKILL.md', userSkill);

  const result = generate({ projectName: 'skill-user', targetDir, onConflict: 'overwrite' });

  assert.equal(result.success, true);
  assert.ok(result.plan.skip.includes('.claude/skills/wf/SKILL.md'));
  assert.equal(result.plan.overwrite.includes('.claude/skills/wf/SKILL.md'), false);
  assert.equal(
    fs.readFileSync(path.join(targetDir, '.claude/skills/wf/SKILL.md'), 'utf8'),
    userSkill,
  );
});

test('install overwrites a Harness-owned .agents/skills/wf/SKILL.md (marker present) under overwrite policy', () => {
  const root = tmpdir();
  const targetDir = path.join(root, 'codex-skill-harness');
  const oldHarness = '---\nharness: wf-agent\n---\nOld codex mirror skill body.\n';
  writeExisting(targetDir, '.agents/skills/wf/SKILL.md', oldHarness);

  const result = generate({ projectName: 'codex-skill-harness', targetDir, onConflict: 'overwrite' });

  assert.equal(result.success, true);
  assert.ok(result.plan.overwrite.includes('.agents/skills/wf/SKILL.md'));
  const after = fs.readFileSync(path.join(targetDir, '.agents/skills/wf/SKILL.md'), 'utf8');
  assert.notEqual(after, oldHarness);
});

// ============================================================================
// Manifest-aware collision protection for OPTIONAL skills (browser-e2e bug fix)
// ============================================================================

test('install preserves a user-owned .claude/skills/browser-e2e/SKILL.md (no marker) under --with browser-e2e overwrite', () => {
  // Regression: optional skill paths used to be missing from the candidate set,
  // so a user no-marker browser-e2e SKILL.md was clobbered under overwrite.
  const root = tmpdir();
  const targetDir = path.join(root, 'browser-e2e-claude-user');
  const userSkill = 'My custom browser-e2e skill.\nPersonal Playwright steps.\n';
  writeExisting(targetDir, '.claude/skills/browser-e2e/SKILL.md', userSkill);
  assert.equal(isHarnessOwnedContent(userSkill), false);

  const result = generate({
    projectName: 'browser-e2e-claude-user',
    targetDir,
    withOptions: ['browser-e2e'],
    onConflict: 'overwrite',
  });

  assert.equal(result.success, true);
  assert.ok(result.plan.skip.includes('.claude/skills/browser-e2e/SKILL.md'));
  assert.equal(result.plan.overwrite.includes('.claude/skills/browser-e2e/SKILL.md'), false);
  assert.ok(
    result.warnings.some(w => /\.claude\/skills\/browser-e2e\/SKILL\.md/.test(w) && /no Harness marker/.test(w)),
    JSON.stringify(result.warnings),
  );
  assert.equal(
    fs.readFileSync(path.join(targetDir, '.claude/skills/browser-e2e/SKILL.md'), 'utf8'),
    userSkill,
  );
});

test('install preserves a user-owned .agents/skills/browser-e2e/SKILL.md (no marker) under --with browser-e2e overwrite', () => {
  const root = tmpdir();
  const targetDir = path.join(root, 'browser-e2e-codex-user');
  const userSkill = 'My custom codex-mirror browser-e2e skill.\nPersonal CDP steps.\n';
  writeExisting(targetDir, '.agents/skills/browser-e2e/SKILL.md', userSkill);
  assert.equal(isHarnessOwnedContent(userSkill), false);

  const result = generate({
    projectName: 'browser-e2e-codex-user',
    targetDir,
    withOptions: ['browser-e2e'],
    onConflict: 'overwrite',
  });

  assert.equal(result.success, true);
  assert.ok(result.plan.skip.includes('.agents/skills/browser-e2e/SKILL.md'));
  assert.equal(result.plan.overwrite.includes('.agents/skills/browser-e2e/SKILL.md'), false);
  assert.equal(
    fs.readFileSync(path.join(targetDir, '.agents/skills/browser-e2e/SKILL.md'), 'utf8'),
    userSkill,
  );
});

test('install overwrites a Harness-owned .claude/skills/browser-e2e/SKILL.md (marker present) under --with browser-e2e overwrite', () => {
  // A prior install leaves a marker; the marker makes the instance Harness-owned
  // so it upgrades normally instead of being protected.
  const root = tmpdir();
  const targetDir = path.join(root, 'browser-e2e-harness');
  const oldHarness = '---\nharness: wf-agent\n---\nOld harness browser-e2e skill body.\n';
  writeExisting(targetDir, '.claude/skills/browser-e2e/SKILL.md', oldHarness);

  const result = generate({
    projectName: 'browser-e2e-harness',
    targetDir,
    withOptions: ['browser-e2e'],
    onConflict: 'overwrite',
  });

  assert.equal(result.success, true);
  assert.ok(result.plan.overwrite.includes('.claude/skills/browser-e2e/SKILL.md'));
  assert.equal(result.plan.skip.includes('.claude/skills/browser-e2e/SKILL.md'), false);
  const after = fs.readFileSync(path.join(targetDir, '.claude/skills/browser-e2e/SKILL.md'), 'utf8');
  assert.notEqual(after, oldHarness);
});

test('install blocks a user-owned .claude/skills/browser-e2e/SKILL.md (no marker) under --with browser-e2e fail and preserves the file', () => {
  const root = tmpdir();
  const targetDir = path.join(root, 'browser-e2e-fail');
  const userSkill = 'My custom browser-e2e skill.\nPersonal Playwright steps.\n';
  writeExisting(targetDir, '.claude/skills/browser-e2e/SKILL.md', userSkill);

  const result = generate({
    projectName: 'browser-e2e-fail',
    targetDir,
    withOptions: ['browser-e2e'],
    onConflict: 'fail',
  });

  assert.equal(result.success, false);
  assert.ok(result.plan.conflict.includes('.claude/skills/browser-e2e/SKILL.md'));
  assert.equal(result.plan.overwrite.includes('.claude/skills/browser-e2e/SKILL.md'), false);
  assert.equal(result.plan.skip.includes('.claude/skills/browser-e2e/SKILL.md'), false);
  assert.equal(
    fs.readFileSync(path.join(targetDir, '.claude/skills/browser-e2e/SKILL.md'), 'utf8'),
    userSkill,
  );
});

test('install never touches a user Harness/tasks/** file (not a write path; preserved untouched)', () => {
  // Harness/tasks/** is preserve-only; user task files are not installer write
  // paths and must never appear in any plan write/overwrite bucket.
  const root = tmpdir();
  const targetDir = path.join(root, 'tasks-preserve');
  const userTask = '# My task progress\nReal user task data.\n';
  writeExisting(targetDir, 'Harness/tasks/my-task/PROGRESS.md', userTask);

  const result = generate({ projectName: 'tasks-preserve', targetDir, onConflict: 'overwrite' });

  assert.equal(result.success, true);
  const allPlanned = [
    ...result.plan.create,
    ...result.plan.overwrite,
    ...result.plan.backup,
    ...result.plan.skip,
    ...result.plan.conflict,
  ];
  assert.equal(allPlanned.includes('Harness/tasks/my-task/PROGRESS.md'), false);
  assert.equal(
    fs.readFileSync(path.join(targetDir, 'Harness/tasks/my-task/PROGRESS.md'), 'utf8'),
    userTask,
  );
});

test('manifest-present: a declared frameworkOwned path (.claude/agents/planner.md) stays protected when the instance has no marker', () => {
  // The manifest declares the path (Harness-interest), but the on-disk INSTANCE
  // has no marker -> still user-owned -> protected. Path declaration does not
  // override instance ownership.
  const manifestPath = path.join(process.cwd(), 'templates/common/Harness/ownership.manifest.json');
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  assert.ok(
    manifest.frameworkOwned.some(e => e.path === '.claude/agents/planner.md'),
    '.claude/agents/planner.md should be declared frameworkOwned in the manifest',
  );

  const root = tmpdir();
  const targetDir = path.join(root, 'manifest-declared-user');
  const userPlanner = 'My personal planner.\nNo harness marker at all.\n';
  writeExisting(targetDir, '.claude/agents/planner.md', userPlanner);
  assert.equal(isHarnessOwnedContent(userPlanner), false);

  const result = generate({ projectName: 'manifest-declared-user', targetDir, onConflict: 'overwrite' });

  assert.equal(result.success, true);
  assert.ok(result.plan.skip.includes('.claude/agents/planner.md'));
  assert.equal(result.plan.overwrite.includes('.claude/agents/planner.md'), false);
  assert.equal(
    fs.readFileSync(path.join(targetDir, '.claude/agents/planner.md'), 'utf8'),
    userPlanner,
  );
});

// ============================================================================
// Candidate-set builder unit tests (manifest-first vs fileSpecs fallback)
// ============================================================================

test('buildHarnessInterestCandidateSet (manifest-present) includes selected optional skill paths like browser-e2e', () => {
  const manifestPath = path.join(process.cwd(), 'templates/common/Harness/ownership.manifest.json');
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  const fileSpecs = [
    { dest: '.claude/skills/browser-e2e/SKILL.md' },
    { dest: '.agents/skills/browser-e2e/SKILL.md' },
  ];
  const selected = [{ id: 'browser-e2e' }];

  const set = buildHarnessInterestCandidateSet(manifest, fileSpecs, selected);

  assert.ok(set.has('.claude/skills/browser-e2e/SKILL.md'));
  assert.ok(set.has('.agents/skills/browser-e2e/SKILL.md'));
});

test('buildHarnessInterestCandidateSet (manifest-present) excludes optional skill paths that are not selected', () => {
  const manifestPath = path.join(process.cwd(), 'templates/common/Harness/ownership.manifest.json');
  const manifest = JSON.parse(fs.readFileSync(manifestPath, 'utf8'));
  const fileSpecs = [{ dest: '.claude/skills/browser-e2e/SKILL.md' }];
  // browser-e2e NOT selected -> its optionalOwned paths must not be candidates.
  const selected = [];

  const set = buildHarnessInterestCandidateSet(manifest, fileSpecs, selected);

  assert.equal(set.has('.claude/skills/browser-e2e/SKILL.md'), false);
});

test('buildHarnessInterestCandidateSet falls back to all fileSpec dests when manifest is absent (null)', () => {
  // Simulates manifest-absent (e.g. a fixture without the source manifest): the
  // candidate set falls back to every fileSpec dest so optional skills stay
  // protected by the marker rule even without the manifest.
  const fileSpecs = [
    { dest: '.claude/skills/browser-e2e/SKILL.md' },
    { dest: '.agents/skills/browser-e2e/SKILL.md' },
    { dest: '.claude/agents/planner.md' },
  ];
  const selected = [{ id: 'browser-e2e' }];

  const set = buildHarnessInterestCandidateSet(null, fileSpecs, selected);

  assert.equal(set.size, fileSpecs.length);
  for (const spec of fileSpecs) assert.ok(set.has(spec.dest));
});
